name: Deploy to GAE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud App Engine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # authenticate with GCP
      - id: "auth"
        name: "Authenticate with GCP"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Deploy to App Engine"
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          working_directory: ./services
          deliverables: ./broker/app.yaml ./logger/app.yaml dispatch.yaml
